//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextBox
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public string FontSize { get; set; }
        public string TextAlign { get; set; }
        public string PaddingTop { get; set; }
        public string PaddingBottom { get; set; }
        public string PaddingLeft { get; set; }
        public string PaddingRight { get; set; }
        public string Top { get; set; }
        public string Bottom { get; set; }
        public string Left { get; set; }
        public string Right { get; set; }
        public string MarginTop { get; set; }
        public string MarginBottom { get; set; }
        public string MarginLeft { get; set; }
        public string MarginRight { get; set; }
        public string LineHeight { get; set; }
        public string FontFamily { get; set; }
        public string Border { get; set; }
        public string BorderStyle { get; set; }
        public string CustomField { get; set; }
    }
}
