//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Column
    {
        public int ColumnId { get; set; }
        public string ColumnClass { get; set; }
        public Nullable<int> RowId { get; set; }
        public string RowClass { get; set; }
        public Nullable<int> PageId { get; set; }
        public string PageDescription { get; set; }
        public Nullable<int> ElementTagId { get; set; }
        public string ElementTag { get; set; }
        public string Id { get; set; }
    }
}
