//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomPage
    {
        public int PageId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> TextId { get; set; }
        public string PageDescription { get; set; }
        public string IsPrivate { get; set; }
        public Nullable<bool> isPublished { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string PageColor { get; set; }
    }
}
