//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomImage
    {
        public int ImageId { get; set; }
        public Nullable<int> PageId { get; set; }
        public string backgroundAttachment { get; set; }
        public string backgroundClip { get; set; }
        public string backgroundImage { get; set; }
        public string backgroundOrigin { get; set; }
        public string backgroundPosition { get; set; }
        public string backgroundRepeat { get; set; }
        public string backgroundSize { get; set; }
        public string background { get; set; }
        public string border { get; set; }
        public string borderBottom { get; set; }
        public string borderBottomColor { get; set; }
        public string borderBottomLeftRadius { get; set; }
        public string borderBottomRightRadius { get; set; }
        public string borderBottomStyle { get; set; }
        public string borderBottomWidth { get; set; }
        public string borderColor { get; set; }
        public string borderImage { get; set; }
        public string borderImageOutset { get; set; }
        public string borderImageRepeat { get; set; }
        public string borderImageSlice { get; set; }
        public string borderImageSource { get; set; }
        public string borderImageWidth { get; set; }
        public string borderLeft { get; set; }
        public string borderLeftColor { get; set; }
        public string borderLeftStyle { get; set; }
        public string borderLeftWidth { get; set; }
        public string borderStyle { get; set; }
        public string borderTop { get; set; }
        public string borderTopColor { get; set; }
        public string borderTopLeftRadius { get; set; }
        public string borderTopRightRadius { get; set; }
        public string borderTopStyle { get; set; }
        public string borderTopWidth { get; set; }
        public string borderWidth { get; set; }
        public string boxShadow { get; set; }
        public byte[] isImage { get; set; }
        public string ImageUrl { get; set; }
    }
}
