//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public int presetId { get; set; }
        public Nullable<int> selectedPresetId { get; set; }
        public string selectedPresetValue { get; set; }
        public string headingColor { get; set; }
        public string headingFontSize { get; set; }
        public string FontFamily { get; set; }
        public string rowColor { get; set; }
        public string columnColor { get; set; }
        public string buttonColor { get; set; }
        public string editIconColor { get; set; }
        public string deleteIconColor { get; set; }
        public string bgImage { get; set; }
        public string rowBgImage { get; set; }
        public string columnBgImage { get; set; }
        public string contentHeaderColor { get; set; }
        public string contentHeaderFontSize { get; set; }
        public string sidebarMenuColor { get; set; }
        public string sidebarTextColor { get; set; }
        public string sidebarHeadingTextColor { get; set; }
        public string selectedPresetName { get; set; }
        public Nullable<bool> isLightMode { get; set; }
        public Nullable<bool> isDarkMode { get; set; }
        public Nullable<bool> isCustom { get; set; }
        public Nullable<bool> isAdvanced { get; set; }
        public string selectedMode { get; set; }
        public string tabFontColor { get; set; }
        public string toolTipColor { get; set; }
        public string lineColor { get; set; }
        public string saveChangesButtonColor { get; set; }
        public string deleteButtonColor { get; set; }
        public string dropdownColor { get; set; }
        public string dropdownFontColor { get; set; }
        public string mobileCardColor { get; set; }
        public string tabletCardColor { get; set; }
        public string laptopCardColor { get; set; }
        public string desktopCardColor { get; set; }
        public string colorOne { get; set; }
        public string colorTwo { get; set; }
        public string colorThree { get; set; }
        public string colorFour { get; set; }
        public string colorFive { get; set; }
        public string colorSix { get; set; }
        public string colorSeven { get; set; }
        public string colorEight { get; set; }
        public string colorNine { get; set; }
        public string colorTen { get; set; }
        public string fontColor { get; set; }
        public string clientUrl { get; set; }
        public string defaultPreset { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public string savedPreset { get; set; }
    }
}
