//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePage
    {
        public int UserID { get; set; }
        public string Header { get; set; }
        public string HeroImageURL { get; set; }
        public string Textbox1 { get; set; }
        public string Textbox2 { get; set; }
        public string Textbox3 { get; set; }
        public string Textbox4 { get; set; }
        public string Textbox5 { get; set; }
        public string Textbox6 { get; set; }
        public string GalleryImageURL { get; set; }
        public string Footer { get; set; }
    }
}
