//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavBar
    {
        public int NavBarId { get; set; }
        public Nullable<int> LogoId { get; set; }
        public string LogoUrl { get; set; }
        public string LogoAlignment { get; set; }
        public string NavBarBgColor { get; set; }
        public string NavBarFontColor { get; set; }
        public string NavBarType { get; set; }
        public string LogoHeight { get; set; }
        public string LogoWidth { get; set; }
        public string LogoPadding { get; set; }
        public string LogoMargin { get; set; }
        public string LogoAnimation { get; set; }
        public string LogoDisplay { get; set; }
        public string LogoOpacity { get; set; }
        public string LogoHyperLink { get; set; }
        public string LogoColor { get; set; }
        public string LogoAttachment { get; set; }
        public string LogoPosition { get; set; }
        public string LogoRepeat { get; set; }
        public string LogoSize { get; set; }
        public string NavBarDisplay { get; set; }
        public string LogoFloat { get; set; }
        public string NavBarPadding { get; set; }
        public string NavBarOverflow { get; set; }
        public string NavBarMargin { get; set; }
        public string NavBarHoverLink { get; set; }
        public string NavBarActiveLink { get; set; }
        public string NavBarFloat { get; set; }
        public string NavBarTextAlign { get; set; }
        public string NavBarTextDecoration { get; set; }
        public string NavBarBorder { get; set; }
        public string NavBarBorderStyle { get; set; }
        public string NavBarOpacity { get; set; }
        public string NavBarPosition { get; set; }
        public string NavBarWebKit { get; set; }
        public string NavTop { get; set; }
        public string NavBottom { get; set; }
        public string NavLeft { get; set; }
        public string NavRight { get; set; }
        public string LogoTop { get; set; }
        public string LogoBottom { get; set; }
        public string LogoLeft { get; set; }
        public string LogoRight { get; set; }
        public string NavBoxShadow { get; set; }
        public string NavMinWidth { get; set; }
        public string NavMaxWidth { get; set; }
        public string NavHeight { get; set; }
        public string NavWidth { get; set; }
        public string LogoMinWidth { get; set; }
        public string LogoMaxWidth { get; set; }
        public string LogoZIndex { get; set; }
        public string NavZIndex { get; set; }
        public string NavListStyleType { get; set; }
        public string NavBorderTop { get; set; }
        public string NavBorderBottom { get; set; }
        public string NavBorderLeft { get; set; }
        public string NavBorderRight { get; set; }
        public string NavImageUrl { get; set; }
        public string NavFontUrl { get; set; }
        public string NavGradient { get; set; }
        public string NavAnimation { get; set; }
        public string NavFontFamily { get; set; }
        public string NavFontSize { get; set; }
        public string NavHyperLink { get; set; }
        public string NavFontLineHeight { get; set; }
        public string NavFontLetterSpacing { get; set; }
        public string ClientUrl { get; set; }
        public Nullable<bool> ClientHasNavbar { get; set; }
    }
}
