//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Row
    {
        public int RowId { get; set; }
        public string RowClass { get; set; }
        public Nullable<bool> isRow { get; set; }
        public Nullable<int> ColumnId { get; set; }
        public Nullable<int> ContainerId { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
