//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadImage
    {
        public int UploadImageId { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageBinary { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> WebContentId { get; set; }
    }
}
