//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTemplateProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        public int UserID { get; set; }
        public string HeroImageURL { get; set; }
        public string Content { get; set; }
        public string GalleryImageURL { get; set; }
    }
}
